# Generated by Django 3.0.8 on 2020-07-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usu_Salas',
            fields=[
                ('usa_id', models.AutoField(primary_key=True, serialize=False)),
                ('salas_sal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Salas')),
                ('usuarios_usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
        ),
    ]
