# Generated by Django 3.0.8 on 2020-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(max_length=250)),
                ('usu_apellido', models.CharField(max_length=250)),
                ('usu_usuario', models.CharField(max_length=250)),
                ('usu_pass', models.CharField(max_length=250)),
                ('usu_correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
