# Generated by Django 3.0.8 on 2020-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('men_id', models.AutoField(primary_key=True, serialize=False)),
                ('men_mensaje', models.CharField(max_length=250)),
            ],
        ),
    ]
