# Generated by Django 3.0.8 on 2020-07-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
        ('usu_salas', '0001_initial'),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='salas_sal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salas.Salas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='usu_salas',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usu_salas.Usu_Salas'),
            preserve_default=False,
        ),
    ]
